services:
  mysql_pokedex:
    image: mysql:8.0
    container_name: pokedex_db
    env_file:
      - .env
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pokedex_db_data:/var/lib/mysql
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pokedex_network

  nest_pokedex:
    image: pokedex_img:latest
    container_name: pokedex_app
    build:
      dockerfile: ./Dockerfile
    depends_on:
      mysql_pokedex:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    networks:
      - pokedex_network

volumes:
  pokedex_db_data: {}
networks:
  pokedex_network:
    driver: bridge