services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pokedex_network

  nest:
    image: nest_img:latest
    container_name: nest_app
    build:
      dockerfile: ./Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    networks:
      - pokedex_network

volumes:
  db_data: {}
networks:
  pokedex_network:
    driver: bridge