name: Deploy NestJS Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    setps:
      - name: Checkout code
        uses: actions/checkout@v3

        - name: Set up Node.js
          uses: action/setup-node@v3
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Build NestJS application
          run: npm run build

        - name: Deploy to Azure
          env:
            SSH_PRIVATE_KEY: $ {{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: $ {{ secrets.SSH_HOST }}
            SSH_USER: $ {{ secrets.SSH_USER }}
          run: |
            rsync -avz --delete dist/ $SSH_USER@SSH_HOST:/pokedex/server/