name: Deploy NestJS Application

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code.
      uses: actions/checkout@v3

    - name: Install SSH and expect.
      run: sudo apt-get install -y sshpass expect

    - name: Build Backend Application.
      run: |
        cd backend
        npm install
        npm run build

    - name: Deploy Backend to VPS.
      env:
        SSH_HOST: ${{ secrets.SSH_HOSTINGER_HOST }}
        SSH_USER: ${{ secrets.SSH_HOSTINGER_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_HOSTINGER_PASSWORD }}
      run: |
        sshpass -p "$SSH_HOSTINGER_PASSWORD" scp -o StrictHostKeyChecking=no -r backend/dist/ $SSH_HOSTINGER_USER@$SSH_HOSTINGER_HOST:~/pokedex_app/server