name: Deploy Angular Application via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Install dependencies.
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Build Application.
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/my-angular-app/
          server-dir: /home/toya4249/listing.toya4249.odns.fr/listing/
          protocol: ftps
