name: Deploy Angular Application

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v3

    - name: Install SSH and expect.
      run: sudo apt-get install -y sshpass expect

    - name: Build Angular Application.
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy Frontend to VPS.
      env:
        SSH_HOST: ${{ secrets.SSH_O2SWITCH_HOST }}
        SSH_USER: ${{ secrets.SSH_O2SWITCH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_O2SWITCH_PASSWORD }}
      run: |
        sshpass -p "$SSH_O2SWITCH_PASSWORD" scp -o StrictHostKeyChecking=no -r frontend/dist/ $SSH_O2SWITCH_USER@$SSH_O2SWITCH_HOST:~/pokedex_app/client