name: Deploy Angular Application

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Install dependencies.
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Build Application.
        run: |
          cd frontend
          npm install
          npm run build

      - name: Publish.
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_O2SWITCH_PRIVATE_KEY }}"
        run: |
          echo -e $SSH_PRIVATE_KEY >__TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          ssh -o StrictHostKeyChecking=no -i __TEMP_INPUT_KEY_FILE "${{ secrets.SSH_HOSTINGER_USER }}"@"${{ secrets.SSH_HOSTINGER_HOST }}" rm -rf /pokedex_app/
          ssh -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -r dist "${{ secrets.SSH_HOSTINGER_USER }}"@"${{ secrets.SSH_HOSTINGER_HOST }}":"/pokdex_app/client/."
          ssh -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -r package.json "${{ secrets.SSH_HOSTINGER_USER }}"@"${{ secrets.SSH_HOSTINGER_HOST }}":"pokdedex_app/client/dist"
          rm __TEMP_INPUT_KEY_FILE
