name: Deploy Angular Application with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH and expect
        run: sudo apt-get install -y sshpass expect

      - name: Build Angular Application
        run: |
          cd frontend
          npm install
          npm run build
      - name: Prepare Deployment Directory
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p ~/pokedex_app/client"
      - name: Deploy Frontend to VPS
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -rf ~/pokedex_app/client/*"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r frontend/dist/ $SSH_USER@$SSH_HOST:~/pokedex_app/client
