name: Deploy NestJS Application

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH and expect
        run: sudo apt-get install -y sshpass expect

      - name: Build NestJS Application
        run: |
          cd backend
          npm install
          npm run build

      - name: Prepare Deployment Directory
        env:
          SSH_HOSTINGER_HOST: ${{ secrets.SSH_HOSTINGER_HOST }}
          SSH_HOSTINGER_HOSTINGER_USER: ${{ secrets.SSH_HOSTINGER_HOSTINGER_USER }}
          SSH_HOSTINGER_HOSTINGER_PASSWORD: ${{ secrets.SSH_HOSTINGER_HOSTINGER_PASSWORD }}
        run: |
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "mkdir -p ~/pokedex_app/server"

      - name: Deploy Backend to VPS
        env:
          SSH_HOSTINGER_HOST: ${{ secrets.SSH_HOSTINGER_HOST }}
          SSH_HOSTINGER_HOSTINGER_USER: ${{ secrets.SSH_HOSTINGER_HOSTINGER_USER }}
          SSH_HOSTINGER_HOSTINGER_PASSWORD: ${{ secrets.SSH_HOSTINGER_HOSTINGER_PASSWORD }}
          USER_DB: ${{ secrets.USER_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "rm -rf ~/pokedex_app/server/*"

          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" scp -o StrictHostKeyChecking=no -r backend/dist/ $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST:~/pokedex_app/server
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" scp -o StrictHostKeyChecking=no backend/package.json backend/package-lock.json $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST:~/pokedex_app/server
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" scp -o StrictHostKeyChecking=no -r backend/prisma $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST:~/pokedex_app/server

          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "echo 'DATABASE_URL=\"mysql://${USER_DB}:${PASSWORD_DB}@localhost:3306/pokedex_db\"' > ~/pokedex_app/server/.env"
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "echo 'JWT_SECRET_KEY=${JWT_SECRET_KEY}' >> ~/pokedex_app/server/.env"

          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "cd ~/pokedex_app/server && npm install --omit=dev"
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "cd ~/pokedex_app/server && npx prisma generate"
          sshpass -p "$SSH_HOSTINGER_HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_HOSTINGER_HOSTINGER_USER@$SSH_HOSTINGER_HOST "cd ~/pokedex_app/server && npx prisma migrate deploy"
