name: Deploy NestJS Application.

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v3

    - name: Install SSH and expect.
      run: sudo apt-get install -y sshpass expect

    - name: Build NestJS Application.
      run: |
        cd backend
        npm install
        npm run build
    - name: Deploy Backend to VPS.
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r backend/dist/ $SSH_USER@$SSH_HOST:~/pokedex_app/server
