name: CI/CD Pipeline Nest Application with Docker to VPS.

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image.
        run: docker build -t nest_app:${{ github.sha }} .

      - name: Save Docker image to file.
        run: docker save -o nest_app.tar nest_app:${{ github.sha }}

      - name: Transfer Docker image and compose to VPS.
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no nest_app.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/pokedex_app/server/
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/pokedex_app/server/

      - name: SSH to VPS and load Docker images.
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            cd ~/pokedex_app/server/
            docker load -i nest_app.tar
            docker-compose down
            docker-compose up -d