name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Publish
        run: |
          echo -e "${{ secrets.SSH_O2SWITCH_PRIVATE_KEY  }}" >__TEMP_INPUT_KEY_FILE

          chmod 600 __TEMP_INPUT_KEY_FILE

          ssh -o StrictHostKeyChecking=no -i __TEMP_INPUT_KEY_FILE -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOSTINGER_USER  }}"@"${{ secrets.SSH_HOSTINGER_HOST  }}" rm -rf /pokedex_app/client

          rm __TEMP_INPUT_KEY_FILE
